//! Server-to-client Huffman compression.
//!
//! # A fixed tree, not a computed one
//!
//! This is not Huffman as a compression algorithm — nothing here counts symbol
//! frequencies or builds a tree. The client has one table baked into its binary
//! and no way to learn another, so the server must use the identical table or
//! the client decodes noise. It is really a fixed prefix code that happens to
//! have been generated by Huffman's algorithm, once, in 1997.
//!
//! That means the table is not tunable and not improvable. It is a constant of
//! the protocol, like a packet id.
//!
//! # What is compressed
//!
//! Server-to-client packets only, and only after the login handshake. The
//! client never compresses anything it sends, so there is no decompressor here
//! — only the encoder in [`compress`]. [`decompress`] exists to test the
//! encoder against, and to read packet captures.
//!
//! Ported from SphereServer's `common/crypto/CHuffman.cpp`.

/// Number of entries: 256 byte values plus the terminator.
const TREE_SIZE: usize = 257;

/// Index of the end-of-stream symbol.
const TERMINAL: usize = 256;

/// The client's baked-in code table.
///
/// Each entry packs a code and its bit length into a `u16`: the low four bits
/// are the length, the remaining twelve are the code, most significant bit
/// first. Entry 256 is the terminator every compressed stream ends with.
///
/// Sphere calls this "the golden key for (0.0.0.0)" and notes the addresses it
/// was lifted from in the 2.0.3 and 2.0.4 client binaries. Do not touch it.
#[rustfmt::skip]
const CODES: [u16; TREE_SIZE] = [
    0x0002, 0x01F5, 0x0226, 0x0347, 0x0757, 0x0286, 0x03B6, 0x0327,
    0x0E08, 0x0628, 0x0567, 0x0798, 0x19D9, 0x0978, 0x02A6, 0x0577,
    0x0718, 0x05B8, 0x1CC9, 0x0A78, 0x0257, 0x04F7, 0x0668, 0x07D8,
    0x1919, 0x1CE9, 0x03F7, 0x0909, 0x0598, 0x07B8, 0x0918, 0x0C68,
    0x02D6, 0x1869, 0x06F8, 0x0939, 0x1CCA, 0x05A8, 0x1AEA, 0x1C0A,
    0x1489, 0x14A9, 0x0829, 0x19FA, 0x1719, 0x1209, 0x0E79, 0x1F3A,
    0x14B9, 0x1009, 0x1909, 0x0136, 0x1619, 0x1259, 0x1339, 0x1959,
    0x1739, 0x1CA9, 0x0869, 0x1E99, 0x0DB9, 0x1EC9, 0x08B9, 0x0859,
    0x00A5, 0x0968, 0x09C8, 0x1C39, 0x19C9, 0x08F9, 0x18F9, 0x0919,
    0x0879, 0x0C69, 0x1779, 0x0899, 0x0D69, 0x08C9, 0x1EE9, 0x1EB9,
    0x0849, 0x1649, 0x1759, 0x1CD9, 0x05E8, 0x0889, 0x12B9, 0x1729,
    0x10A9, 0x08D9, 0x13A9, 0x11C9, 0x1E1A, 0x1E0A, 0x1879, 0x1DCA,
    0x1DFA, 0x0747, 0x19F9, 0x08D8, 0x0E48, 0x0797, 0x0EA9, 0x0E19,
    0x0408, 0x0417, 0x10B9, 0x0B09, 0x06A8, 0x0C18, 0x0717, 0x0787,
    0x0B18, 0x14C9, 0x0437, 0x0768, 0x0667, 0x04D7, 0x08A9, 0x02F6,
    0x0C98, 0x0CE9, 0x1499, 0x1609, 0x1BAA, 0x19EA, 0x39FA, 0x0E59,
    0x1949, 0x1849, 0x1269, 0x0307, 0x06C8, 0x1219, 0x1E89, 0x1C1A,
    0x11DA, 0x163A, 0x385A, 0x3DBA, 0x17DA, 0x106A, 0x397A, 0x24EA,
    0x02E7, 0x0988, 0x33CA, 0x32EA, 0x1E9A, 0x0BF9, 0x3DFA, 0x1DDA,
    0x32DA, 0x2EDA, 0x30BA, 0x107A, 0x2E8A, 0x3DEA, 0x125A, 0x1E8A,
    0x0E99, 0x1CDA, 0x1B5A, 0x1659, 0x232A, 0x2E1A, 0x3AEB, 0x3C6B,
    0x3E2B, 0x205A, 0x29AA, 0x248A, 0x2CDA, 0x23BA, 0x3C5B, 0x251A,
    0x2E9A, 0x252A, 0x1EA9, 0x3A0B, 0x391B, 0x23CA, 0x392B, 0x3D5B,
    0x233A, 0x2CCA, 0x390B, 0x1BBA, 0x3A1B, 0x3C4B, 0x211A, 0x203A,
    0x12A9, 0x231A, 0x3E0B, 0x29BA, 0x3D7B, 0x202A, 0x3ADB, 0x213A,
    0x253A, 0x32CA, 0x23DA, 0x23FA, 0x32FA, 0x11CA, 0x384A, 0x31CA,
    0x17CA, 0x30AA, 0x2E0A, 0x276A, 0x250A, 0x3E3B, 0x396A, 0x18FA,
    0x204A, 0x206A, 0x230A, 0x265A, 0x212A, 0x23EA, 0x3ACB, 0x393B,
    0x3E1B, 0x1DEA, 0x3D6B, 0x31DA, 0x3E5B, 0x3E4B, 0x207A, 0x3C7B,
    0x277A, 0x3D4B, 0x0C08, 0x162A, 0x3DAA, 0x124A, 0x1B4A, 0x264A,
    0x33DA, 0x1D1A, 0x1AFA, 0x39EA, 0x24FA, 0x373B, 0x249A, 0x372B,
    0x1679, 0x210A, 0x23AA, 0x1B8A, 0x3AFB, 0x18EA, 0x2ECA, 0x0627,
    0x00D4,
];

/// Compress a server-to-client packet.
///
/// Appends the terminator, so the output is a complete stream. The result can be
/// *longer* than the input — the table is tuned for typical packet content, and
/// incompressible bytes cost more than eight bits each. Callers that care must
/// compare and decide; this function always compresses.
///
/// ```
/// use openshard_protocol::huffman;
///
/// let packet = [0x1Bu8, 0x00, 0x00, 0x00, 0x01];
/// let wire = huffman::compress(&packet);
/// assert_eq!(huffman::decompress(&wire).unwrap(), packet);
/// ```
pub fn compress(input: &[u8]) -> Vec<u8> {
    // Most packets shrink; this is a guess, not a bound.
    let mut output = Vec::with_capacity(input.len());
    let mut accumulator: u8 = 0;
    let mut filled: u8 = 0;

    let mut push_symbol = |symbol: usize, output: &mut Vec<u8>| {
        let entry = CODES[symbol];
        let mut remaining = (entry & 0xF) as u8;
        let code = entry >> 4;
        while remaining > 0 {
            remaining -= 1;
            accumulator = (accumulator << 1) | ((code >> remaining) & 1) as u8;
            filled += 1;
            if filled == 8 {
                output.push(accumulator);
                accumulator = 0;
                filled = 0;
            }
        }
    };

    for byte in input {
        push_symbol(*byte as usize, &mut output);
    }
    push_symbol(TERMINAL, &mut output);

    if filled > 0 {
        // Pad the last byte with zeros on the right. The terminator is what
        // tells the decoder to stop, so these bits are never read — but they
        // must be written, since the wire unit is a byte.
        output.push(accumulator << (8 - filled));
    }
    output
}

/// A compressed stream could not be read.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[non_exhaustive]
pub enum HuffmanError {
    /// The bits ran out before the terminator did. The stream is truncated, or
    /// was never a compressed stream.
    Truncated,
    /// A bit sequence matched no code.
    ///
    /// Unreachable for anything [`compress`] produced; reachable for a corrupt
    /// or hostile capture.
    InvalidCode,
}

impl core::fmt::Display for HuffmanError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Truncated => f.write_str("compressed stream ended before its terminator"),
            Self::InvalidCode => f.write_str("compressed stream held an unknown code"),
        }
    }
}

impl std::error::Error for HuffmanError {}

/// Decompress a stream produced by [`compress`].
///
/// The client never sends compressed data, so this is not on any hot path. It
/// exists so the encoder can be tested against a real inverse rather than
/// against itself, and so packet captures can be read.
///
/// Decoding walks bit by bit against the table. That is O(bits x table) and slow,
/// which is fine for a function nothing calls in production.
pub fn decompress(input: &[u8]) -> Result<Vec<u8>, HuffmanError> {
    let mut output = Vec::new();
    let mut code: u16 = 0;
    let mut length: u8 = 0;

    for byte in input {
        for shift in (0..8).rev() {
            code = (code << 1) | u16::from((byte >> shift) & 1);
            length += 1;

            // A code is at most 11 bits wide, so anything longer than that
            // cannot become a match no matter what follows.
            if length > MAX_CODE_BITS {
                return Err(HuffmanError::InvalidCode);
            }

            let Some(symbol) = lookup(code, length) else {
                continue;
            };
            if symbol == TERMINAL {
                return Ok(output);
            }
            output.push(symbol as u8);
            code = 0;
            length = 0;
        }
    }

    // Trailing padding bits without a terminator: the stream was cut short.
    Err(HuffmanError::Truncated)
}

/// Widest code in the table. Asserted by a test rather than trusted.
const MAX_CODE_BITS: u8 = 11;

/// Find the symbol whose code is exactly `code` in `length` bits.
///
/// Total because the table is a prefix code: no code is a prefix of another, so
/// at most one entry can match.
fn lookup(code: u16, length: u8) -> Option<usize> {
    CODES
        .iter()
        .position(|entry| (entry & 0xF) as u8 == length && (entry >> 4) == code)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_a_valid_prefix_code() {
        // The property that makes decoding unambiguous. If any code were a
        // prefix of another, a decoder could not know where a symbol ended, and
        // the client would render garbage for some inputs and not others.
        for (i, first) in CODES.iter().enumerate() {
            let (code_a, len_a) = (first >> 4, (first & 0xF) as u8);
            assert!(len_a > 0, "entry {i} has no length");
            assert!(len_a <= MAX_CODE_BITS, "entry {i} is {len_a} bits");
            assert!(code_a < (1 << len_a), "entry {i} code overflows its length");

            for (j, second) in CODES.iter().enumerate().skip(i + 1) {
                let (code_b, len_b) = (second >> 4, (second & 0xF) as u8);
                let (short, long, shift) = if len_a <= len_b {
                    (code_a, code_b, len_b - len_a)
                } else {
                    (code_b, code_a, len_a - len_b)
                };
                assert_ne!(long >> shift, short, "code {i} is a prefix of code {j}");
            }
        }
    }

    #[test]
    fn the_table_matches_spheres_golden_key() {
        // Spot-checks against CHuffman.cpp. The client has this table baked in;
        // a single wrong entry makes it decode noise, so it is pinned here.
        assert_eq!(CODES.len(), 257);
        assert_eq!(CODES[0], 0x0002, "first entry");
        assert_eq!(CODES[1], 0x01F5);
        assert_eq!(CODES[255], 0x0627, "last byte value");
        assert_eq!(CODES[TERMINAL], 0x00D4, "terminator: 0b1101, four bits");
    }

    #[test]
    fn round_trips_a_login_packet() {
        // 0x1B start-of-game, roughly.
        let packet = [
            0x1B, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x90, 0x00, 0x00, 0x00, 0x00,
        ];
        let wire = compress(&packet);
        assert_eq!(decompress(&wire).unwrap(), packet);
    }

    #[test]
    fn round_trips_every_single_byte() {
        for byte in 0..=u8::MAX {
            let wire = compress(&[byte]);
            assert_eq!(decompress(&wire).unwrap(), vec![byte], "byte 0x{byte:02X}");
        }
    }

    #[test]
    fn round_trips_every_byte_pair_boundary() {
        // Two symbols in a row is where bit packing across a byte boundary goes
        // wrong, and the codes are 2..11 bits, so pairs cover every alignment.
        for a in [0u8, 1, 0x7F, 0x80, 0xFE, 0xFF] {
            for b in 0..=u8::MAX {
                let input = [a, b];
                assert_eq!(
                    decompress(&compress(&input)).unwrap(),
                    input,
                    "pair {a:02X} {b:02X}"
                );
            }
        }
    }

    #[test]
    fn round_trips_a_long_packet() {
        let input: Vec<u8> = (0..2000).map(|i| (i % 256) as u8).collect();
        assert_eq!(decompress(&compress(&input)).unwrap(), input);
    }

    #[test]
    fn an_empty_packet_is_just_the_terminator() {
        // 0x00D4 is 0b1101 in four bits, padded right to one byte: 0b1101_0000.
        assert_eq!(compress(&[]), vec![0b1101_0000]);
        assert_eq!(decompress(&compress(&[])).unwrap(), Vec::<u8>::new());
    }

    #[test]
    fn compression_actually_compresses_typical_packets() {
        // Real packets are full of zeros and low bytes, which is what the table
        // is tuned for. If this ever regresses the table is wrong.
        let packet = [0u8; 64];
        assert!(
            compress(&packet).len() < packet.len(),
            "64 zero bytes must shrink"
        );
    }

    #[test]
    fn compression_can_grow_incompressible_data() {
        // Documented, not a bug: a caller that must not grow has to compare.
        let packet: Vec<u8> = (0..64).map(|i| 0x80 + (i % 64)).collect();
        let wire = compress(&packet);
        assert!(
            wire.len() > packet.len(),
            "high bytes cost more than 8 bits each; got {} from {}",
            wire.len(),
            packet.len()
        );
    }

    #[test]
    fn a_truncated_stream_is_an_error_not_a_panic() {
        let wire = compress(&[1, 2, 3, 4, 5, 6, 7, 8]);
        assert_eq!(
            decompress(&wire[..wire.len() - 1]),
            Err(HuffmanError::Truncated)
        );
        assert_eq!(decompress(&[]), Err(HuffmanError::Truncated));
    }

    #[test]
    fn junk_does_not_hang_the_decoder() {
        // Not from a real client, but a capture tool will feed this eventually.
        for junk in [vec![0xFF; 16], vec![0x00; 16], vec![0xAA, 0x55, 0xAA, 0x55]] {
            let _ = decompress(&junk);
        }
    }
}
