//! Turns `data/doors.json` into the table [`crate::doors`] looks a graphic up in.
//!
//! Twenty-two families out of the source and into a data file, for the reason
//! every other table in this workspace moved: the shape a content pack ships is
//! a data file, a shard with a door of its own edits one line, and a list of
//! magic constants in the middle of a module about occlusion reads as noise
//! wherever it is put.
//!
//! What is emitted is a sorted array of `(base, count, name)`, so the lookup is a
//! binary search rather than a match arm per family. The order is this build's,
//! not the file's: a lookup that assumed the file was sorted would answer wrongly
//! for exactly one family and nobody would notice.
//!
//! The count is per family and not a constant, because it is not one number:
//! most doors use all eight `DoorFacing` values and are sixteen graphics wide,
//! and the three sliding doors use four and are eight. Reading that as sixteen
//! made `PaperSlidingDoor` claim `ClothSlidingDoor`'s graphics and call half of
//! them by the wrong parity.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data");
    println!("cargo:rerun-if-changed=src/shaders");

    // `docs/lighting_raymarch.md`'s backlog item on the `place` format:
    // compiled here rather than checked in, so `src/shaders/place_format.wesl`
    // stays the one place its constants are written. Each entry's
    // `include_str!(concat!(env!("OUT_DIR"), ...))` counterpart lives beside
    // its own `create_shader_module` — `renderer.rs` for the three below.
    let wesl = wesl::Wesl::new("src/shaders");
    for name in ["ground", "statics", "mesh_face", "select", "blit"] {
        wesl.build_artifact(&format!("package::{name}").parse().unwrap(), name);
    }

    let path = Path::new("data").join("doors.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));

    // Hand-parsed rather than with `serde_json`: this crate has no dependencies
    // of its own for a reason (see its `Cargo.toml`), and adding one to the
    // *build* graph to read twenty-two rows is a poor trade. The file is written
    // by hand and read by this, and the panics below are what keeps that pair
    // honest — a build that cannot read the table fails loudly rather than
    // emitting an empty one, which would silently turn every door back into a
    // wall.
    let mut families: Vec<(u16, u16, String)> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if !line.starts_with("{ \"base\"") {
            continue;
        }
        let base = field(line, "\"base\":").trim_matches('"');
        let base = u16::from_str_radix(base.trim_start_matches("0x"), 16)
            .unwrap_or_else(|e| panic!("{}: base in {line:?}: {e}", path.display()));
        let count = field(line, "\"count\":")
            .parse::<u16>()
            .unwrap_or_else(|e| panic!("{}: count in {line:?}: {e}", path.display()));
        assert!(
            count >= 2 && count % 2 == 0,
            "{}: {line:?} — a family is an even number of leaves, shut and open",
            path.display(),
        );
        let name = field(line, "\"name\":").trim_matches('"').to_string();
        families.push((base, count, name));
    }
    assert!(
        families.len() >= 22,
        "{}: read {} families, which is fewer than the ServUO classes there are",
        path.display(),
        families.len(),
    );
    families.sort_unstable();
    for pair in families.windows(2) {
        assert!(
            pair[0].0 + pair[0].1 <= pair[1].0,
            "{}: {} at {:#06X} runs {} graphics into {} at {:#06X}",
            path.display(),
            pair[0].2,
            pair[0].0,
            pair[0].1,
            pair[1].2,
            pair[1].0,
        );
    }

    let mut out = String::from("// @generated by build.rs from data/doors.json.\n\n");
    writeln!(
        out,
        "/// Every door family: its first graphic — the shut leaf of facing 0 — how\n\
         /// many graphics it covers, and the name ServUO gives it. Sorted by graphic\n\
         /// so the lookup can bisect.\n\
         const FAMILIES: [(u16, u16, &str); {}] = [",
        families.len()
    )
    .unwrap();
    for (base, count, name) in &families {
        writeln!(out, "    ({base:#06X}, {count}, {name:?}),").unwrap();
    }
    out.push_str("];\n");

    std::fs::write(Path::new(&out_dir).join("doors.rs"), out).expect("writing doors.rs");
}

/// The value after `key` on a one-line JSON object, up to the next comma or brace.
fn field<'a>(line: &'a str, key: &str) -> &'a str {
    let rest = line
        .split_once(key)
        .unwrap_or_else(|| panic!("no {key} in {line:?}"))
        .1;
    rest.split([',', '}']).next().expect("split yields one").trim()
}
